name: AMR_fleet_management
description: A comprehensive fleet management system for Automated Guided Vehicles (AMRs) with real-time control, mapping, and analytics.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  # UI and Material Design
  cupertino_icons: ^1.0.6
  material_design_icons_flutter: ^7.0.7296

  # Navigation and State Management
  provider: ^6.0.5
  go_router: ^12.0.0

  # Network and API
  http: ^1.1.0
  dio: ^5.3.2
  web_socket_channel: ^2.4.0
  connectivity_plus: ^5.0.1

  # Data Storage and Preferences
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # JSON and Serialization
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1

  # DateTime and Utilities
  intl: ^0.18.1
  uuid: ^4.1.0
  equatable: ^2.0.5

  # Charts and Visualization
  fl_chart: ^0.64.0
  syncfusion_flutter_charts: ^23.1.36

  # File Handling and Media
  file_picker: ^8.0.7
  image_picker: ^1.0.4
  path: ^1.8.3

  # UI Components and Animations
  lottie: ^2.6.0
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_slidable: ^3.0.0

  # Maps and Location (if needed for facility maps)
  geolocator: ^10.1.0
  geocoding: ^2.1.1

  # Permissions
  permission_handler: ^12.0.0+1

  # Device Info and System
  device_info_plus: ^9.1.0
  package_info_plus: ^4.2.0

  # QR Code and Barcode (for device identification)
  qr_flutter: ^4.1.0

  # Logging and Debugging
  logger: ^2.0.2+1
  flutter_launcher_icons: ^0.14.4
  network_info_plus: ^6.1.4
  multicast_dns: ^0.3.3
  network_tools: ^5.0.6
  yaml: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting and Code Quality
  flutter_lints: ^3.0.1
  very_good_analysis: ^5.1.0

  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  freezed: ^2.4.6
  hive_generator: ^2.0.1

  # Testing
  mockito: ^5.4.2
  bloc_test: ^9.1.4
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/login_logo.png
    # - assets/icons/
    - assets/app_logo.png
    - assets/TW_WHITE.png

  # Fonts
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
        - asset: fonts/Roboto-Light.ttf
          weight: 300

# Flutter configuration
flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/app_logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/app_logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/app_logo.png"

# Analysis options
dependency_overrides:
  # Add any package overrides here if needed

# Platform specific configurations
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#2196F3"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"